development:
  adapter: postgresql
  encoding: unicode
  database: sm6_development
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sm6_test
  host: localhost
  port: 5432
  min_messages: error