:ruby: ree
:application: sixminutestory.com
:user: rails
#:time_zone: UTC
:deploy_to: /srv/sixminutestory.com/
:domain: sixminutestory.com
:domain_aliases:
  - www.sixminutestory.com
#  - assets2.yourapp.com
#:scm: git
:repository: git@galen.unfuddle.com:galen/sms.git
# Use :app_symlinks to setup directories under public/ that you want to persist
# across deployments. They'll be symlinked to the shared directory.
#:app_symlinks:
#  - uploads
#
# Use :local_config to copy directories straight from your local project directory
# to the server: these are files that you don't have/want in scm.
:local_config:
  - config/database.yml
#
# The entries in shared_children are created in #{application}/shared
:shared_children:
- system
- log
- pids
- config
- db
- tmp
# After specifying a gem with config.gem, run 'rake moonshine:gems'
# to update config/gems.yml. If the gem depends on native packages, 
# tell Moonshine here:
#:apt_gems:
#  :awesomegem:
#    - awesome
#    - libawesome-dev
#
# See all the options for Passenger, Apache vhosts, and MySQL in the
# respective templates: moonshine/lib/moonshine/manifest/rails/templates
:ssh:
  :port:27777
  :allow_users:
    - rails
:passenger:
  :max_pool_size: 2
  :use_global_queue: true
:mysql:
  :default_storage_engine: MyISAM
  :innodb_buffer_pool_size: 32M
  :auto_increment_increment: 1