development:
  min_infix_len: 3
  enable_star: true
  
production:
  pid_file: /home/rails/www/sixminutestory.com/shared/tmp/searchd.pid
  searchd_files: /home/rails/www/sixminutestory.com/shared/db/sphinx
  bin_path: '/usr/local/bin'
  min_infix_len: 3
  enable_star: true
  
